# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0002_auto_20161211_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
