# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentari', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postis_contenti', models.CharField(max_length=2000)),
                ('postis_satauri', models.CharField(max_length=50)),
                ('sheqmnis_dro', models.DateTimeField(verbose_name='sheqmnis dro')),
                ('surati', models.ImageField(upload_to='app')),
                ('ganaxlebis_dro', models.DateTimeField(verbose_name='gaaxlebis dro')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='posti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Post'),
        ),
    ]
