# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ganaxlebis_dro',
            field=models.DateTimeField(verbose_name='განახლების დრო'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postis_contenti',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='post',
            name='sheqmnis_dro',
            field=models.DateTimeField(verbose_name='შექმნის დრო'),
        ),
    ]
