# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161211_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'კომენტარები'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'პოსტები'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='komentari',
            field=models.CharField(max_length=200, verbose_name='კომენტარი'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Post', verbose_name='პოსტი'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postis_contenti',
            field=models.TextField(verbose_name='კონტენტი'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postis_satauri',
            field=models.CharField(max_length=50, verbose_name='სათაური'),
        ),
        migrations.AlterField(
            model_name='post',
            name='surati',
            field=models.ImageField(upload_to='app', verbose_name='სურათი'),
        ),
    ]
