# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161215_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Post', verbose_name='პოსტი'),
        ),
    ]
