# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161215_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='posti',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(to='app.Comment', verbose_name='კომენტარი'),
        ),
    ]
