# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161215_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ganaxlebis_dro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='განახლების დრო'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sheqmnis_dro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შექმნის დრო'),
        ),
    ]
