# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161215_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='surati',
            field=models.ImageField(blank=True, null=True, upload_to='app', verbose_name='სურათი'),
        ),
    ]
